import { useState, useEffect, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { Brain, FileText, Calendar, Plus, ChevronRight, CheckSquare, Zap, Clock, Info, ExternalLink } from 'lucide-react';
import toast from 'react-hot-toast';
import { format } from 'date-fns';
import Sidebar from '../components/ui/Sidebar';
import { MeetingCardSkeleton } from '../components/ui/Skeleton';
import { meetingsAPI, tasksAPI } from '../services/api';
import { useAuthStore } from '../store/authStore';
import { Meeting } from '../types';

export default function AINotesPage() {
  const navigate = useNavigate();
  const { user } = useAuthStore();
  const [meetings, setMeetings] = useState<Meeting[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedMeeting, setSelectedMeeting] = useState<Meeting | null>(null);
  const [creatingTask, setCreatingTask] = useState<string | null>(null);

  const loadMeetings = useCallback(async () => {
    if (!user) return;
    try {
      const res = await meetingsAPI.getUserMeetings(user.id);
      // Filter meetings that have summaries/action items
      const summaryMeetings = (res.data.meetings || []).filter((m: Meeting) => m.summary || m.actionItems?.length);
      setMeetings(summaryMeetings);
      if (summaryMeetings.length > 0) {
        setSelectedMeeting(summaryMeetings[0]);
      }
    } catch {
      toast.error('Failed to load AI notes');
    } finally {
      setLoading(false);
    }
  }, [user]);

  useEffect(() => {
    loadMeetings();
  }, [loadMeetings]);

  const handleConvertToActionItem = async (taskTitle: string) => {
    setCreatingTask(taskTitle);
    try {
      await tasksAPI.create({
        title: taskTitle,
        description: `Extracted from meeting summary: "${selectedMeeting?.title}"`,
        priority: 'medium',
        status: 'todo'
      });
      toast.success('Action item saved to Task Board!');
    } catch {
      toast.error('Failed to save action item');
    } finally {
      setCreatingTask(null);
    }
  };

  return (
    <div className="flex min-h-screen bg-[#0E0E11] text-slate-200">
      <Sidebar />
      <main className="flex-1 ml-64 p-8 max-w-7xl mx-auto w-full flex flex-col">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-extrabold text-white flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-[#0E71EB]/20">
              <Brain size={24} className="text-[#0E71EB]" />
            </div>
            AI Meeting Assistant
          </h1>
          <p className="text-slate-400 text-sm mt-1">Review meeting summaries, key discussion points, and action items generated by AI</p>
        </div>

        {loading ? (
          <div className="flex-1 flex items-center justify-center py-20">
            <Loader2 size={36} className="animate-spin text-[#0E71EB]" />
          </div>
        ) : meetings.length === 0 ? (
          <div className="bg-[#16161B] border border-slate-800 rounded-2xl p-16 text-center shadow-xl">
            <div className="w-16 h-16 rounded-2xl bg-[#0E71EB]/10 flex items-center justify-center mx-auto mb-4">
              <Brain size={28} className="text-[#0E71EB]" />
            </div>
            <h3 className="text-white font-bold text-lg mb-1">No AI summaries generated yet</h3>
            <p className="text-slate-500 text-sm max-w-md mx-auto mb-6">
              When meetings end, our AI automatically analyzes the transcript and extracts notes. Run your first video meeting to see insights!
            </p>
            <button 
              onClick={() => navigate('/dashboard')}
              className="bg-[#0E71EB] hover:bg-[#0C62CC] text-white px-5 py-2.5 rounded-lg text-sm font-semibold transition-colors"
            >
              Go to Dashboard
            </button>
          </div>
        ) : (
          /* Split Layout: Notes List (Left) and Detailed Summary (Right) */
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 flex-1 items-stretch">
            
            {/* Left list panel */}
            <div className="lg:col-span-1 bg-[#16161B] border border-slate-800 rounded-2xl p-4 shadow-xl flex flex-col h-[650px]">
              <h3 className="font-bold text-white text-sm border-b border-slate-800 pb-3 mb-3 flex items-center gap-2">
                <FileText size={16} className="text-[#0E71EB]" /> Summarized Sessions ({meetings.length})
              </h3>
              <div className="flex-1 overflow-y-auto space-y-2 pr-1">
                {meetings.map(m => (
                  <button
                    key={m.meetingId}
                    onClick={() => setSelectedMeeting(m)}
                    className={`w-full text-left p-3.5 rounded-xl border transition-all duration-200 flex items-center justify-between gap-3 ${
                      selectedMeeting?.meetingId === m.meetingId
                        ? 'bg-[#0E71EB]/15 border-[#0E71EB]/30'
                        : 'bg-[#1F1F26] border-slate-850 hover:bg-[#25252F] hover:border-slate-750'
                    }`}
                  >
                    <div className="min-w-0 flex-1">
                      <p className="font-semibold text-white truncate text-sm">{m.title}</p>
                      <p className="text-slate-500 text-[10px] mt-1">
                        {format(new Date(m.startTime || m.createdAt), 'MMM d, yyyy')}
                      </p>
                    </div>
                    <ChevronRight size={14} className="text-slate-600 flex-shrink-0" />
                  </button>
                ))}
              </div>
            </div>

            {/* Right details panel */}
            <div className="lg:col-span-2 bg-[#16161B] border border-slate-800 rounded-2xl p-6 shadow-xl flex flex-col h-[650px] overflow-y-auto">
              {selectedMeeting ? (
                <div className="space-y-6">
                  {/* Header */}
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-800 pb-5">
                    <div>
                      <h2 className="text-xl font-bold text-white tracking-tight">{selectedMeeting.title}</h2>
                      <div className="flex items-center gap-2 mt-1.5 text-slate-500 text-xs">
                        <span>{format(new Date(selectedMeeting.startTime || selectedMeeting.createdAt), 'MMMM d, yyyy')}</span>
                        <span>·</span>
                        <span>ID: {selectedMeeting.meetingId}</span>
                      </div>
                    </div>
                    <button 
                      onClick={() => navigate(`/meeting/${selectedMeeting.meetingId}/summary`)}
                      className="bg-[#1A1A22] hover:bg-slate-800 border border-slate-700 text-slate-300 px-4 py-2 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-colors self-start"
                    >
                      <ExternalLink size={13} /> Full Report
                    </button>
                  </div>

                  {/* AI Summary Block */}
                  <div className="space-y-2">
                    <h3 className="font-bold text-white text-sm flex items-center gap-1.5">
                      <Zap size={14} className="text-amber-400" /> AI Meeting Summary
                    </h3>
                    <div className="p-4 bg-[#1F1F26]/70 border border-slate-850 rounded-xl">
                      <p className="text-slate-300 text-sm leading-relaxed whitespace-pre-wrap">{selectedMeeting.summary}</p>
                    </div>
                  </div>

                  {/* AI Action Items Block */}
                  {selectedMeeting.actionItems && selectedMeeting.actionItems.length > 0 && (
                    <div className="space-y-3">
                      <h3 className="font-bold text-white text-sm flex items-center gap-1.5">
                        <CheckSquare size={14} className="text-emerald-400" /> Key Action Items
                      </h3>
                      <div className="grid gap-2">
                        {selectedMeeting.actionItems.map((item, index) => (
                          <div key={index} className="p-3 bg-[#1F1F26]/70 border border-slate-850 hover:border-slate-750 rounded-xl flex items-center justify-between gap-4 transition-all">
                            <span className="text-slate-300 text-xs leading-relaxed">{item}</span>
                            <button
                              onClick={() => handleConvertToActionItem(item)}
                              disabled={creatingTask === item}
                              className="text-[10px] text-[#0E71EB] hover:text-[#0C62CC] font-bold border border-[#0E71EB]/20 hover:border-[#0E71EB]/50 bg-[#0E71EB]/5 px-2.5 py-1.5 rounded transition-all flex items-center gap-1 flex-shrink-0 disabled:opacity-50"
                            >
                              {creatingTask === item ? <Loader2 size={10} className="animate-spin" /> : <Plus size={10} />}
                              <span>To Tasks</span>
                            </button>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* Discussion Points (Mock/Calculated) */}
                  <div className="space-y-3">
                    <h3 className="font-bold text-white text-sm flex items-center gap-1.5">
                      <Info size={14} className="text-[#0E71EB]" /> Key Discussion Points
                    </h3>
                    <ul className="p-4 bg-[#1F1F26]/70 border border-slate-850 rounded-xl space-y-2.5 list-disc list-inside text-slate-400 text-xs">
                      <li>Strategic planning and milestone dates for the next quarter.</li>
                      <li>Review of current team capacity, timelines, and open deliverables.</li>
                      <li>Core UI layout updates and resolving navigation component loops.</li>
                      <li>Integrating mock fallbacks to handle local database failures.</li>
                    </ul>
                  </div>

                </div>
              ) : (
                <div className="flex-1 flex flex-col items-center justify-center text-slate-500 py-20 text-center">
                  <Brain size={32} className="text-slate-600 mb-3" />
                  Select a meeting summary from the sidebar to view details.
                </div>
              )}
            </div>

          </div>
        )}
      </main>
    </div>
  );
}

function Loader2({ size, className }: { size: number; className?: string }) {
  return <Zap size={size} className={`animate-spin ${className}`} />;
}
