import { useState } from 'react';
import { Bot, Loader2, CheckCircle2, Sparkles, RefreshCw } from 'lucide-react';
import { aiAPI } from '../../services/api';
import toast from 'react-hot-toast';
import { AISummary } from '../../types';

interface AIPanelProps {
  meetingId: string;
  meetingTitle?: string;
  duration?: number;
  participantCount?: number;
  chatMessages?: string[];
}

export default function AIPanel({ meetingId, meetingTitle, duration, participantCount, chatMessages }: AIPanelProps) {
  const [loading, setLoading] = useState(false);
  const [summary, setSummary] = useState<AISummary | null>(null);

  const generate = async () => {
    setLoading(true);
    try {
      const { data } = await aiAPI.generateSummary({
        meetingTitle,
        duration,
        participantCount,
        chatMessages,
      });
      setSummary(data);
      toast.success('AI summary generated!');
    } catch (err) {
      toast.error('Failed to generate summary');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex flex-col h-full">
      <div className="px-4 py-3 border-b border-white/5">
        <div className="flex items-center gap-2">
          <Bot size={14} className="text-brand-400" />
          <h3 className="font-semibold text-sm">AI Assistant</h3>
        </div>
        <p className="text-white/30 text-xs mt-0.5">Powered by IntellMeet AI</p>
      </div>

      <div className="flex-1 overflow-y-auto p-4">
        {!summary && !loading && (
          <div className="text-center py-8">
            <div className="w-12 h-12 bg-brand-600/15 rounded-xl flex items-center justify-center mx-auto mb-3">
              <Sparkles size={20} className="text-brand-400" />
            </div>
            <p className="text-sm text-white/60 mb-1 font-medium">Generate AI Summary</p>
            <p className="text-xs text-white/30 mb-6">Get a smart summary and action items from your meeting</p>
            <button onClick={generate} className="btn-primary mx-auto">
              <Sparkles size={14} /> Generate Summary
            </button>
          </div>
        )}

        {loading && (
          <div className="text-center py-8">
            <Loader2 size={24} className="animate-spin text-brand-400 mx-auto mb-3" />
            <p className="text-sm text-white/60">AI is analyzing your meeting...</p>
            <p className="text-xs text-white/30 mt-1">This may take a moment</p>
          </div>
        )}

        {summary && (
          <div className="space-y-4 animate-fade-in">
            <div>
              <div className="flex items-center justify-between mb-2">
                <h4 className="text-xs font-semibold text-white/60 uppercase tracking-wider">Summary</h4>
                <button onClick={generate} className="text-white/30 hover:text-white/60" title="Regenerate">
                  <RefreshCw size={12} />
                </button>
              </div>
              <div className="bg-surface-700 rounded-lg p-3 text-sm text-white/80 leading-relaxed">
                {summary.summary}
              </div>
            </div>

            <div>
              <h4 className="text-xs font-semibold text-white/60 uppercase tracking-wider mb-2">Action Items</h4>
              <div className="space-y-2">
                {summary.actionItems.map((item: string, i: number) => (
                  <div key={i} className="flex items-start gap-2 p-2 bg-surface-700 rounded-lg">
                    <CheckCircle2 size={14} className="text-brand-400 mt-0.5 flex-shrink-0" />
                    <p className="text-sm text-white/80">{item}</p>
                  </div>
                ))}
              </div>
            </div>

            <p className="text-[10px] text-white/20 text-center">
              Generated by {summary.model}
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
